/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTelemetryRouteImport } from './routes/admin.telemetry'
import { Route as AdminNotifyRouteImport } from './routes/admin.notify'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as ActivateTokenRouteImport } from './routes/activate.$token'
import { Route as ApiPublicTutorialsRouteImport } from './routes/api/public/tutorials'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicControlRouteImport } from './routes/api/public/control'
import { Route as ApiPublicSteamTrendingRouteImport } from './routes/api/public/steam/trending'
import { Route as ApiPublicSteamDailyRouteImport } from './routes/api/public/steam/daily'
import { Route as ApiPublicSteamCatalogRouteImport } from './routes/api/public/steam/catalog'
import { Route as ApiPublicSteamBlacklistRouteImport } from './routes/api/public/steam/blacklist'
import { Route as ApiPublicSessionStatusRouteImport } from './routes/api/public/session/status'
import { Route as ApiPublicSessionCreateRouteImport } from './routes/api/public/session/create'
import { Route as ApiPublicSessionActivateRouteImport } from './routes/api/public/session/activate'
import { Route as ApiPublicPremiumStatusRouteImport } from './routes/api/public/premium.status'
import { Route as ApiPublicPremiumRedeemRouteImport } from './routes/api/public/premium.redeem'

const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelemetryRoute = AdminTelemetryRouteImport.update({
  id: '/admin/telemetry',
  path: '/admin/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotifyRoute = AdminNotifyRouteImport.update({
  id: '/admin/notify',
  path: '/admin/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/admin/codes',
  path: '/admin/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/admin/api',
  path: '/admin/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateTokenRoute = ActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTutorialsRoute = ApiPublicTutorialsRouteImport.update({
  id: '/api/public/tutorials',
  path: '/api/public/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicControlRoute = ApiPublicControlRouteImport.update({
  id: '/api/public/control',
  path: '/api/public/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamTrendingRoute = ApiPublicSteamTrendingRouteImport.update({
  id: '/api/public/steam/trending',
  path: '/api/public/steam/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamDailyRoute = ApiPublicSteamDailyRouteImport.update({
  id: '/api/public/steam/daily',
  path: '/api/public/steam/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamCatalogRoute = ApiPublicSteamCatalogRouteImport.update({
  id: '/api/public/steam/catalog',
  path: '/api/public/steam/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamBlacklistRoute = ApiPublicSteamBlacklistRouteImport.update({
  id: '/api/public/steam/blacklist',
  path: '/api/public/steam/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionStatusRoute = ApiPublicSessionStatusRouteImport.update({
  id: '/api/public/session/status',
  path: '/api/public/session/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionCreateRoute = ApiPublicSessionCreateRouteImport.update({
  id: '/api/public/session/create',
  path: '/api/public/session/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionActivateRoute =
  ApiPublicSessionActivateRouteImport.update({
    id: '/api/public/session/activate',
    path: '/api/public/session/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPremiumStatusRoute = ApiPublicPremiumStatusRouteImport.update({
  id: '/api/public/premium/status',
  path: '/api/public/premium/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPremiumRedeemRoute = ApiPublicPremiumRedeemRouteImport.update({
  id: '/api/public/premium/redeem',
  path: '/api/public/premium/redeem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/public/premium/redeem': typeof ApiPublicPremiumRedeemRoute
  '/api/public/premium/status': typeof ApiPublicPremiumStatusRoute
  '/api/public/session/activate': typeof ApiPublicSessionActivateRoute
  '/api/public/session/create': typeof ApiPublicSessionCreateRoute
  '/api/public/session/status': typeof ApiPublicSessionStatusRoute
  '/api/public/steam/blacklist': typeof ApiPublicSteamBlacklistRoute
  '/api/public/steam/catalog': typeof ApiPublicSteamCatalogRoute
  '/api/public/steam/daily': typeof ApiPublicSteamDailyRoute
  '/api/public/steam/trending': typeof ApiPublicSteamTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/public/premium/redeem': typeof ApiPublicPremiumRedeemRoute
  '/api/public/premium/status': typeof ApiPublicPremiumStatusRoute
  '/api/public/session/activate': typeof ApiPublicSessionActivateRoute
  '/api/public/session/create': typeof ApiPublicSessionCreateRoute
  '/api/public/session/status': typeof ApiPublicSessionStatusRoute
  '/api/public/steam/blacklist': typeof ApiPublicSteamBlacklistRoute
  '/api/public/steam/catalog': typeof ApiPublicSteamCatalogRoute
  '/api/public/steam/daily': typeof ApiPublicSteamDailyRoute
  '/api/public/steam/trending': typeof ApiPublicSteamTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/public/premium/redeem': typeof ApiPublicPremiumRedeemRoute
  '/api/public/premium/status': typeof ApiPublicPremiumStatusRoute
  '/api/public/session/activate': typeof ApiPublicSessionActivateRoute
  '/api/public/session/create': typeof ApiPublicSessionCreateRoute
  '/api/public/session/status': typeof ApiPublicSessionStatusRoute
  '/api/public/steam/blacklist': typeof ApiPublicSteamBlacklistRoute
  '/api/public/steam/catalog': typeof ApiPublicSteamCatalogRoute
  '/api/public/steam/daily': typeof ApiPublicSteamDailyRoute
  '/api/public/steam/trending': typeof ApiPublicSteamTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/docs'
    | '/download'
    | '/activate/$token'
    | '/admin/api'
    | '/admin/codes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notify'
    | '/admin/telemetry'
    | '/api/public/control'
    | '/api/public/telemetry'
    | '/api/public/tutorials'
    | '/api/public/premium/redeem'
    | '/api/public/premium/status'
    | '/api/public/session/activate'
    | '/api/public/session/create'
    | '/api/public/session/status'
    | '/api/public/steam/blacklist'
    | '/api/public/steam/catalog'
    | '/api/public/steam/daily'
    | '/api/public/steam/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/docs'
    | '/download'
    | '/activate/$token'
    | '/admin/api'
    | '/admin/codes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notify'
    | '/admin/telemetry'
    | '/api/public/control'
    | '/api/public/telemetry'
    | '/api/public/tutorials'
    | '/api/public/premium/redeem'
    | '/api/public/premium/status'
    | '/api/public/session/activate'
    | '/api/public/session/create'
    | '/api/public/session/status'
    | '/api/public/steam/blacklist'
    | '/api/public/steam/catalog'
    | '/api/public/steam/daily'
    | '/api/public/steam/trending'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/docs'
    | '/download'
    | '/activate/$token'
    | '/admin/api'
    | '/admin/codes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notify'
    | '/admin/telemetry'
    | '/api/public/control'
    | '/api/public/telemetry'
    | '/api/public/tutorials'
    | '/api/public/premium/redeem'
    | '/api/public/premium/status'
    | '/api/public/session/activate'
    | '/api/public/session/create'
    | '/api/public/session/status'
    | '/api/public/steam/blacklist'
    | '/api/public/steam/catalog'
    | '/api/public/steam/daily'
    | '/api/public/steam/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  ActivateTokenRoute: typeof ActivateTokenRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotifyRoute: typeof AdminNotifyRoute
  AdminTelemetryRoute: typeof AdminTelemetryRoute
  ApiPublicControlRoute: typeof ApiPublicControlRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
  ApiPublicTutorialsRoute: typeof ApiPublicTutorialsRoute
  ApiPublicPremiumRedeemRoute: typeof ApiPublicPremiumRedeemRoute
  ApiPublicPremiumStatusRoute: typeof ApiPublicPremiumStatusRoute
  ApiPublicSessionActivateRoute: typeof ApiPublicSessionActivateRoute
  ApiPublicSessionCreateRoute: typeof ApiPublicSessionCreateRoute
  ApiPublicSessionStatusRoute: typeof ApiPublicSessionStatusRoute
  ApiPublicSteamBlacklistRoute: typeof ApiPublicSteamBlacklistRoute
  ApiPublicSteamCatalogRoute: typeof ApiPublicSteamCatalogRoute
  ApiPublicSteamDailyRoute: typeof ApiPublicSteamDailyRoute
  ApiPublicSteamTrendingRoute: typeof ApiPublicSteamTrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telemetry': {
      id: '/admin/telemetry'
      path: '/admin/telemetry'
      fullPath: '/admin/telemetry'
      preLoaderRoute: typeof AdminTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notify': {
      id: '/admin/notify'
      path: '/admin/notify'
      fullPath: '/admin/notify'
      preLoaderRoute: typeof AdminNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/admin/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/admin/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$token': {
      id: '/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof ActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tutorials': {
      id: '/api/public/tutorials'
      path: '/api/public/tutorials'
      fullPath: '/api/public/tutorials'
      preLoaderRoute: typeof ApiPublicTutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/control': {
      id: '/api/public/control'
      path: '/api/public/control'
      fullPath: '/api/public/control'
      preLoaderRoute: typeof ApiPublicControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/trending': {
      id: '/api/public/steam/trending'
      path: '/api/public/steam/trending'
      fullPath: '/api/public/steam/trending'
      preLoaderRoute: typeof ApiPublicSteamTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/daily': {
      id: '/api/public/steam/daily'
      path: '/api/public/steam/daily'
      fullPath: '/api/public/steam/daily'
      preLoaderRoute: typeof ApiPublicSteamDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/catalog': {
      id: '/api/public/steam/catalog'
      path: '/api/public/steam/catalog'
      fullPath: '/api/public/steam/catalog'
      preLoaderRoute: typeof ApiPublicSteamCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/blacklist': {
      id: '/api/public/steam/blacklist'
      path: '/api/public/steam/blacklist'
      fullPath: '/api/public/steam/blacklist'
      preLoaderRoute: typeof ApiPublicSteamBlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/session/status': {
      id: '/api/public/session/status'
      path: '/api/public/session/status'
      fullPath: '/api/public/session/status'
      preLoaderRoute: typeof ApiPublicSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/session/create': {
      id: '/api/public/session/create'
      path: '/api/public/session/create'
      fullPath: '/api/public/session/create'
      preLoaderRoute: typeof ApiPublicSessionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/session/activate': {
      id: '/api/public/session/activate'
      path: '/api/public/session/activate'
      fullPath: '/api/public/session/activate'
      preLoaderRoute: typeof ApiPublicSessionActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/premium/status': {
      id: '/api/public/premium/status'
      path: '/api/public/premium/status'
      fullPath: '/api/public/premium/status'
      preLoaderRoute: typeof ApiPublicPremiumStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/premium/redeem': {
      id: '/api/public/premium/redeem'
      path: '/api/public/premium/redeem'
      fullPath: '/api/public/premium/redeem'
      preLoaderRoute: typeof ApiPublicPremiumRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  ActivateTokenRoute: ActivateTokenRoute,
  AdminApiRoute: AdminApiRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotifyRoute: AdminNotifyRoute,
  AdminTelemetryRoute: AdminTelemetryRoute,
  ApiPublicControlRoute: ApiPublicControlRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
  ApiPublicTutorialsRoute: ApiPublicTutorialsRoute,
  ApiPublicPremiumRedeemRoute: ApiPublicPremiumRedeemRoute,
  ApiPublicPremiumStatusRoute: ApiPublicPremiumStatusRoute,
  ApiPublicSessionActivateRoute: ApiPublicSessionActivateRoute,
  ApiPublicSessionCreateRoute: ApiPublicSessionCreateRoute,
  ApiPublicSessionStatusRoute: ApiPublicSessionStatusRoute,
  ApiPublicSteamBlacklistRoute: ApiPublicSteamBlacklistRoute,
  ApiPublicSteamCatalogRoute: ApiPublicSteamCatalogRoute,
  ApiPublicSteamDailyRoute: ApiPublicSteamDailyRoute,
  ApiPublicSteamTrendingRoute: ApiPublicSteamTrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
